Repository lumen/lumen, pull requests merged in 2020-01, with the labels that each got.

#365 Add timestamp/0 and now/0
  lumen_runtime/src/otp/erlang.rs
  lumen_runtime/src/otp/erlang/now_0.rs
  lumen_runtime/src/otp/erlang/timestamp_0.rs
  lumen_runtime/src/otp/erlang/timestamp_0/test.rs
  lumen_runtime/src/system/time.rs
Labels: enhancement, runtime:BIFs

#379 Use try_into.unwrap_or_else instead of is_tuple for ok_n_input check …
  examples/spawn-chain/src/elixir/chain/on_submit_1/label_2.rs
  liblumen_alloc/src/erts/term/arch/arch_32.rs
  liblumen_alloc/src/erts/term/arch/arch_64.rs
  liblumen_alloc/src/erts/term/arch/arch_x86_64.rs
Labels: bug, enhancement

#382 Ensure native functions are re-entrant by peeking arguments from stack instead of popping stack immediately
  examples/spawn-chain/src/elixir/chain/create_processes_2.rs
  examples/spawn-chain/src/elixir/chain/create_processes_2/label_3.rs
  examples/spawn-chain/src/elixir/chain/none_1/test.rs
  examples/spawn-chain/src/elixir/chain/none_output_1.rs
  examples/spawn-chain/src/elixir/chain/on_submit_1/label_4.rs
  examples/spawn-chain/src/elixir/chain/run_2/label_2.rs
  examples/spawn-chain/src/elixir/enum/reduce_3.rs
  examples/spawn-chain/src/elixir/enum/reduce_range_inc_4.rs
  examples/spawn-chain/src/elixir/enum/reduce_range_inc_4/label_1.rs
  examples/spawn-chain/src/elixir/io/puts_1.rs
  liblumen_alloc/src/erts/process.rs
  liblumen_alloc/src/erts/process/code.rs
  liblumen_alloc/src/erts/process/gc/young_heap.rs
  liblumen_eir_interpreter/src/call_result.rs
  liblumen_eir_interpreter/src/code.rs
  lumen_runtime/proptest-regressions/otp/erlang/apply_2/test/with_function/with_empty_list_arguments.txt
  lumen_runtime/proptest-regressions/otp/erlang/apply_2/test/with_function/with_non_empty_proper_list_arguments.txt
  lumen_runtime/src/future.rs
  lumen_runtime/src/otp/erlang/apply_2.rs
  lumen_runtime/src/otp/erlang/apply_2/test/with_function/with_empty_list_arguments.rs
  lumen_runtime/src/otp/erlang/apply_2/test/with_function/with_non_empty_proper_list_arguments.rs
  lumen_runtime/src/otp/erlang/apply_3.rs
  lumen_runtime/src/otp/erlang/spawn_1/test/with_function/with_arity_zero.rs
  lumen_runtime/src/otp/erlang/spawn_link_1/test/with_function/with_arity_zero/without_environment.rs
  lumen_runtime/src/otp/erlang/spawn_monitor_1/test/with_function/with_arity_zero/without_environment.rs
  lumen_runtime/src/otp/erlang/spawn_opt_2/test/with_function/with_empty_list_options/with_arity_zero.rs
  lumen_runtime/src/otp/erlang/spawn_opt_2/test/with_function/with_link_and_monitor_in_options_list/with_arity_zero/without_environment.rs
  lumen_runtime/src/otp/erlang/spawn_opt_2/test/with_function/with_link_in_options_list/with_arity_zero/without_environment.rs
  lumen_runtime/src/otp/erlang/spawn_opt_2/test/with_function/with_monitor_in_options_list/with_arity_zero/without_environment.rs
  lumen_runtime/src/otp/erlang/timestamp_0/test.rs
  lumen_runtime/src/otp/timer/tc_3.rs
  lumen_runtime/src/otp/timer/tc_3/label_1.rs
  lumen_runtime/src/otp/timer/tc_3/label_3.rs
  lumen_runtime/src/otp/timer/tc_3/label_4.rs
  lumen_runtime/src/otp/timer/tc_3/label_5.rs
  lumen_runtime_macros/src/lib.rs
  lumen_web/src/wait/with_return_0.rs
  lumen_web/src/window/on_submit_1.rs
Labels: bug, enhancement

#383 Fix npm link name in README
  examples/interpreter-in-browser/README.md
Labels: bug

#384 npm audit fix
  examples/interpreter-in-browser/www/package-lock.json
  examples/interpreter-in-browser/www/package.json
  examples/spawn-chain/www/package-lock.json
  examples/spawn-chain/www/package.json
Labels: bug

#362 Implement IOList BIFs
  liblumen_alloc/src/erts/term/binary/aligned_binary.rs
  lumen_runtime/proptest-regressions/otp/erlang/binary_to_float_1/test.txt
  lumen_runtime/src/context.rs
  lumen_runtime/src/context/type.rs
  lumen_runtime/src/macros/exception.rs
  lumen_runtime/src/otp/erlang.rs
  lumen_runtime/src/otp/erlang/binary_to_float_1.rs
  lumen_runtime/src/otp/erlang/binary_to_float_1/test.rs
  lumen_runtime/src/otp/erlang/binary_to_integer_1.rs
  lumen_runtime/src/otp/erlang/binary_to_integer_1/test/with_binary.rs
  lumen_runtime/src/otp/erlang/binary_to_integer_2.rs
  lumen_runtime/src/otp/erlang/binary_to_integer_2/test.rs
  lumen_runtime/src/otp/erlang/iolist_or_binary.rs
  lumen_runtime/src/otp/erlang/iolist_size_1.rs
  lumen_runtime/src/otp/erlang/iolist_size_1/test.rs
  lumen_runtime/src/otp/erlang/iolist_to_binary_1.rs
  lumen_runtime/src/otp/erlang/iolist_to_binary_1/test.rs
  lumen_runtime/src/otp/erlang/iolist_to_iovec_1.rs
  lumen_runtime/src/otp/erlang/iolist_to_iovec_1/test.rs
  lumen_runtime/src/otp/erlang/list_to_binary_1.rs
  lumen_runtime/src/otp/erlang/list_to_float_1.rs
  lumen_runtime/src/otp/erlang/list_to_float_1/test.rs
  lumen_runtime/src/otp/erlang/list_to_integer_1.rs
  lumen_runtime/src/otp/erlang/list_to_integer_1/test/with_list.rs
  lumen_runtime/src/otp/erlang/list_to_integer_2.rs
  lumen_runtime/src/otp/erlang/list_to_integer_2/test.rs
  lumen_runtime/src/otp/erlang/string_to_float.rs
  lumen_runtime/src/otp/erlang/string_to_integer.rs
  lumen_runtime/src/test/strategy/term.rs
  lumen_runtime/src/test/strategy/term/list.rs
  lumen_runtime/src/test/strategy/term/list/io.rs
Labels: enhancement

#386 group_leader/0
  liblumen_alloc/src/erts/process.rs
  lumen_runtime/src/otp/erlang.rs
  lumen_runtime/src/otp/erlang/group_leader_0.rs
  lumen_runtime/src/otp/erlang/group_leader_0/test.rs
  lumen_runtime/src/process/spawn/options.rs
Labels: enhancement

#387 group_leader/2
  liblumen_alloc/src/erts/process.rs
  lumen_runtime/src/otp/erlang.rs
  lumen_runtime/src/otp/erlang/group_leader_0.rs
  lumen_runtime/src/otp/erlang/group_leader_2.rs
  lumen_runtime/src/otp/erlang/group_leader_2/test.rs
  lumen_runtime/src/otp/erlang/group_leader_2/test/with_group_leader_pid.rs
  lumen_runtime/src/otp/erlang/group_leader_2/test/with_group_leader_pid/with_pid_pid.rs
  lumen_runtime/src/otp/erlang/group_leader_2/test/with_group_leader_pid/with_pid_pid/with_group_leader_alive.rs
  lumen_runtime/src/otp/erlang/group_leader_2/test/with_group_leader_pid/with_pid_pid/with_group_leader_alive/with_other_group_leader.rs
  lumen_runtime/src/otp/erlang/group_leader_2/test/with_group_leader_pid/with_pid_pid/with_group_leader_alive/with_other_group_leader/with_pid_alive.rs
  lumen_runtime/src/otp/erlang/group_leader_2/test/with_group_leader_pid/with_pid_pid/with_group_leader_alive/with_other_group_leader/with_pid_alive/without_self_pid.rs
  lumen_runtime/src/otp/erlang/group_leader_2/test/with_group_leader_pid/with_pid_pid/with_group_leader_alive/with_self_group_leader.rs
  lumen_runtime/src/otp/erlang/group_leader_2/test/with_group_leader_pid/with_pid_pid/with_group_leader_alive/with_self_group_leader/with_pid_alive.rs
Labels: enhancement
